#!/usr/bin/env bash
# Configuration loading utilities for 3x-ui VPN automation
# Source this file in your bash scripts to load .env configuration with defaults.

set -euo pipefail

# Check if functions already defined to allow idempotent sourcing
if ! command -v load_config >/dev/null 2>&1; then
    # Determine script directory to source dependencies
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    
    # Source logging utilities
    # shellcheck source=logging.sh
    source "${SCRIPT_DIR}/logging.sh"
    
    # Source validation utilities (for validation after loading)
    # shellcheck source=validate-config.sh
    source "${SCRIPT_DIR}/validate-config.sh"
    
    # Source reality utilities (for key generation)
    # shellcheck source=reality-utils.sh
    source "${SCRIPT_DIR}/reality-utils.sh"
    
    # ------------------------------------------------------------------------
    # Configuration Loading Functions
    # ------------------------------------------------------------------------
    
    # Generate a UUID if not already set
    # Uses uuidgen, falls back to /proc/sys/kernel/random/uuid
    generate_uuid() {
        if [[ -z "${UUID:-}" ]]; then
            if command -v uuidgen >/dev/null 2>&1; then
                UUID="$(uuidgen)"
                log_info "Generated UUID: ${UUID}"
            elif [[ -f /proc/sys/kernel/random/uuid ]]; then
                UUID="$(cat /proc/sys/kernel/random/uuid)"
                log_info "Generated UUID: ${UUID}"
            else
                log_error "Cannot generate UUID: uuidgen not available and /proc/sys/kernel/random/uuid not found."
                log_error "Please install uuid-runtime or set UUID manually in .env"
                exit 1
            fi
        fi
    }
    
    # Load configuration from .env file with defaults
    # Usage: load_config [config_file_path]
    load_config() {
        local config_file="${1:-}"
        
        # Determine config file path
        if [[ -z "${config_file}" ]]; then
            # Default: .env in project root (two levels up from scripts/common/)
            config_file="$(cd "${SCRIPT_DIR}/../.." && pwd)/.env"
        fi
        
        # Check if config file exists
        if [[ ! -f "${config_file}" ]]; then
            log_error "Configuration file not found: ${config_file}"
            log_error "Copy .env.example to .env and fill in required parameters."
            exit 1
        fi
        
        log_info "Loading configuration from: ${config_file}"
        
        # Source the configuration file
        # shellcheck source=/dev/null
        source "${config_file}"
        
        # --------------------------------------------------------------------
        # Set defaults for required parameters (if empty or unset)
        # --------------------------------------------------------------------
        
        # Server IPs (no defaults, validation will catch if empty)
        
        # SSH configuration (no defaults)
        
        # VLESS protocol
        export VLESS_PORT="${VLESS_PORT:-443}"
        export TRANSPORT="${TRANSPORT:-TCP}"
        export SECURITY="${SECURITY:-reality}"
        
        # Reality parameters
        export SERVER_NAMES="${SERVER_NAMES:-cloudflare.com}"
        export DEST="${DEST:-cloudflare.com:443}"
        # SHORT_IDS, PRIVATE_KEY, PUBLIC_KEY can be empty (will be generated)
        
        # Optional features
        export ENABLE_WARP="${ENABLE_WARP:-false}"
        export ENABLE_REVERSE_PROXY="${ENABLE_REVERSE_PROXY:-false}"
        # DOMAIN has no default
        
        # Advanced settings (optional)
        export SSH_PORT="${SSH_PORT:-22}"
        export PANEL_PORT="${PANEL_PORT:-2053}"
        export PANEL_USERNAME="${PANEL_USERNAME:-admin}"
        # PANEL_PASSWORD has no default (will be generated by 3x-ui install)
        export ROUTING_RU_GEOIP="${ROUTING_RU_GEOIP:-geosite:category-ru}"
        
        # --------------------------------------------------------------------
        # Generate missing values
        # --------------------------------------------------------------------
        
        # Generate UUID if not provided
        generate_uuid
        export UUID
        
        # Generate Reality keys if not provided
        generate_reality_keys
        
        # Generate short IDs if not provided
        generate_short_ids
        
        # --------------------------------------------------------------------
        # Validate the loaded configuration
        # --------------------------------------------------------------------
        
        validate_config
        
        log_success "Configuration loaded successfully."
    }
    
    # Export functions for use in other scripts
    export -f load_config generate_uuid
    
    # If script is executed directly (not sourced), run load_config
    if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        load_config "$@"
    fi
fi